#!/bin/bash

cd /home/ipol/ipolDevel/cp2
source bin/activate

NAME="cp2"                                  # Name of the application
DJANGODIR=/home/ipol/ipolDevel/cp2/ControlPanel             # Django project directory
SOCKFILE=/home/ipol/ipolDevel/cp2/ControlPanel/run/gunicorn.sock  # we will communicte using this unix socket
USER=ipol                                        # the user to run as
                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=ControlPanel.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=ControlPanel.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
cd ControlPanel/
exec gunicorn ControlPanel.wsgi \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=- \


