#!/bin/bash

# THIS SCRIPT DELETE TMP DIRECTORY AND FINAL DIRECTORY IMAGES
# FROM CONFIGURATION FILE GIVEN IN PARAMATER
# CALL SCRIPT DATABASE

SCRIPT=`readlink -f "$0"`
PATH_INIT=`dirname $SCRIPT`
DB_SCRIPT='/db/script'
DATABASE='blob.db'
TEST='test/error.txt'
SLASH='/'
DEL=false
PATH_SCRIPT=$PATH_INIT$DB_SCRIPT
PATH_DB=$PATH_INIT$SLASH$DATABASE
FILE_ARG=''

if  [[ ("$#" -eq 2 && ($1 == "-g") && ( -f $2 )) ]]
then
    DEL=true
    FILE_ARG="$2"
elif [[ ("$#" -eq 1 && ( -f $1 )) ]]
then
    FILE_ARG="$1"
else
    echo "Usage: $0 [-g] file.conf"
    exit
fi

echo "Script $0 processing"

mapfile < $FILE_ARG
SIZEFILE=`wc -l < $FILE_ARG`
echo "FILE_ARG=$FILE_ARG"
echo "SIZEFILE=$SIZEFILE"

i=0
while [[ "$i" != "$SIZEFILE" ]]
do
    if [[ "${MAPFILE[i]}" =~ "tmp.dir" ]]
    then
      TMP=${MAPFILE[i]:11:-2}
    elif [[ "${MAPFILE[i]}" =~ "final.dir" ]]
    then
      INPUT_DIR=${MAPFILE[i]:13:-2}
    elif [[ "${MAPFILE[i]}" =~ "thumbnail.dir" ]]
    then
      THUMB=${MAPFILE[i]:17:-2}
    fi
    (( i++ ))
done

PATH_ERROR=$PATH_INIT$SLASH$TEST

if [[ "$INPUT_DIR" != "" ]]
then
    PATH_DIR=$PATH_INIT$SLASH$INPUT_DIR
    PATH_TMP=$PATH_INIT$SLASH$TMP
    PATH_THUMB=$PATH_INIT$SLASH$THUMB
fi

if [ -e $PATH_DIR ]
then
    rm -r $PATH_DIR
    rm -r $PATH_TMP
    rm -r $PATH_THUMB
    if [ -e $PATH_ERROR ]
    then
	rm $PATH_ERROR
    fi
fi

echo "running $PATH_SCRIPT"
bash $PATH_SCRIPT

echo "DEL = $DEL"
if [ $DEL == true ]
then
    echo "rm $PATH_DB"
    rm $PATH_DB
    echo "rm $PATH_ERROR"
    rm $PATH_ERROR
fi

echo "Script $0 ending"
