-- MySQL Script generated by MySQL Workbench
-- mer. 24 juin 2015 15:35:05 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema images
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `blob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `hash` VARCHAR(70) NULL,
  `format` VARCHAR(30) NULL,
  `title` VARCHAR(255) NULL,
  `credit` LONGTEXT NULL);


-- -----------------------------------------------------
-- Table `demo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(30) NULL);


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `tags` VARCHAR(70) NULL);


-- -----------------------------------------------------
-- Table `blob_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob_tags` (
  `id_blob` INTEGER,
  `id_tags` INTEGER,
  PRIMARY KEY (`id_blob`, `id_tags`),
  CONSTRAINT `fk_blob_has_tags_blob1`
    FOREIGN KEY (`id_blob`)
    REFERENCES `blob` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_blob_has_tags_tags1`
    FOREIGN KEY (`id_tags`)
    REFERENCES `tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);

CREATE INDEX `fk_blob_has_tags_tags1_idx` ON `blob_tags` (`id_tags` ASC);

CREATE INDEX `fk_blob_has_tags_blob1_idx` ON `blob_tags` (`id_blob` ASC);


-- -----------------------------------------------------
-- Table `blob_demo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob_demo` (
  `id_blob` INTEGER,
  `id_demo` INTEGER,
  PRIMARY KEY (`id_blob`, `id_demo`),
  CONSTRAINT `fk_blob_has_demo_blob1`
    FOREIGN KEY (`id_blob`)
    REFERENCES `blob` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_blob_has_demo_demo1`
    FOREIGN KEY (`id_demo`)
    REFERENCES `demo` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);

CREATE INDEX `fk_blob_has_demo_demo1_idx` ON `blob_demo` (`id_demo` ASC);

CREATE INDEX `fk_blob_has_demo_blob1_idx` ON `blob_demo` (`id_blob` ASC);


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
