-- MySQL Script generated by MySQL Workbench
-- mar. 16 juin 2015 13:25:17 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema images
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `blob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `hash` VARCHAR(70) NULL,
  `format` VARCHAR(30) NULL,
  `title` VARCHAR(255) NULL,
  `credit` LONGTEXT NULL);


-- -----------------------------------------------------
-- Table `app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(30) NULL);


-- -----------------------------------------------------
-- Table `blob_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob_app` (
  `id_blob` INTEGER,
  `id_app` INTEGER,
  PRIMARY KEY (`id_blob`, `id_app`),
  CONSTRAINT `fk_image_has_app_image`
    FOREIGN KEY (`id_blob`)
    REFERENCES `blob` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_has_app_app1`
    FOREIGN KEY (`id_app`)
    REFERENCES `app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_image_has_app_app1_idx` ON `blob_app` (`id_app` ASC);

CREATE INDEX `fk_image_has_app_image_idx` ON `blob_app` (`id_blob` ASC);


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `tags` VARCHAR(70) NULL);


-- -----------------------------------------------------
-- Table `blob_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob_tags` (
  `id_blob` INTEGER,
  `id_tags` INTEGER,
  PRIMARY KEY (`id_blob`, `id_tags`),
  CONSTRAINT `fk_blob_has_tags_blob1`
    FOREIGN KEY (`id_blob`)
    REFERENCES `blob` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blob_has_tags_tags1`
    FOREIGN KEY (`id_tags`)
    REFERENCES `tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_blob_has_tags_tags1_idx` ON `blob_tags` (`id_tags` ASC);

CREATE INDEX `fk_blob_has_tags_blob1_idx` ON `blob_tags` (`id_blob` ASC);


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
