-- MySQL Script generated by MySQL Workbench
-- lun. 29 juin 2015 16:24:56 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema images
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `blob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `hash` VARCHAR(70) NULL,
  `format` VARCHAR(30) NULL,
  `extension` VARCHAR(30) NULL,
  `title` VARCHAR(255) NULL,
  `credit` LONGTEXT NULL);


-- -----------------------------------------------------
-- Table `demo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(30) NULL);


-- -----------------------------------------------------
-- Table `tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tag` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(70) NULL);


-- -----------------------------------------------------
-- Table `blob_demo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob_demo` (
  `id_blob` INTEGER,
  `id_demo` INTEGER,
  PRIMARY KEY (`id_blob`, `id_demo`),
  CONSTRAINT `fk_blob_has_demo_blob1`
    FOREIGN KEY (`id_blob`)
    REFERENCES `blob` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_blob_has_demo_demo1`
    FOREIGN KEY (`id_demo`)
    REFERENCES `demo` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);

CREATE INDEX `fk_blob_has_demo_demo1_idx` ON `blob_demo` (`id_demo` ASC);

CREATE INDEX `fk_blob_has_demo_blob1_idx` ON `blob_demo` (`id_blob` ASC);


-- -----------------------------------------------------
-- Table `blob_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blob_tag` (
  `id_blob` INTEGER,
  `id_tag` INTEGER,
  PRIMARY KEY (`id_blob`, `id_tag`),
  CONSTRAINT `fk_blob_has_tag_blob1`
    FOREIGN KEY (`id_blob`)
    REFERENCES `blob` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_blob_has_tag_tag1`
    FOREIGN KEY (`id_tag`)
    REFERENCES `tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);

CREATE INDEX `fk_blob_has_tag_tag1_idx` ON `blob_tag` (`id_tag` ASC);

CREATE INDEX `fk_blob_has_tag_blob1_idx` ON `blob_tag` (`id_blob` ASC);


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
