PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS "demo" (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	VARCHAR(30),
	`is_template`	BOOLEAN DEFAULT 0,
	`template_id`	INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "blob" (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`hash`	VARCHAR(70) NOT NULL,
	`format`	VARCHAR(30),
	`extension`	VARCHAR(30),
	`title`	VARCHAR(255),
	`credit`	LONGTEXT
);
CREATE TABLE IF NOT EXISTS "tag" (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	VARCHAR(70) NOT NULL
);
CREATE TABLE IF NOT EXISTS "blob_tag" (
	`blob_id`	INTEGER NOT NULL,
	`tag_id`	INTEGER NOT NULL,
	PRIMARY KEY(blob_id,tag_id),
	FOREIGN KEY(`blob_id`) REFERENCES "blob" ( `id` ) ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(`tag_id`) REFERENCES "tag" ( `id` ) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS "demo_blob" (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`blob_id`	INTEGER NOT NULL,
	`demo_id`	INTEGER NOT NULL,
	`blob_set`	VARCHAR(70) DEFAULT NULL,
	`blob_pos_in_set`	INTEGER,
	FOREIGN KEY(`blob_id`) REFERENCES "blob" ( `id` ) ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(`demo_id`) REFERENCES "demo" ( `id` ) ON DELETE CASCADE ON UPDATE RESTRICT
);

