#!/bin/bash

# THIS SCRIPT DELETE DATABASE (*.db)
# CREATE A NEW DATABASE FROM SQL FILE
# COPY THE NEW DB FILE IN CURRENT DIRECTORY

echo "Script $0 processing"

SCRIPT=`readlink -f "$0"`
PATH_SCRIPT=`dirname $SCRIPT`
DB='blob.db'
SQL='blob.sql'
SLASH='/'
PATH_DB=$PATH_SCRIPT$SLASH$DB
PATH_SQL=$PATH_SCRIPT$SLASH$SQL
DEST=${PATH_SCRIPT%/*}


if [ -f $PATH_DB ]
then
    rm $PATH_DB
fi

sqlite3 $PATH_DB < $PATH_SQL
cp $PATH_DB $DEST
rm $PATH_DB

echo "Script $0 ending"

