[default]
compilation_root = "./compilation/"
execution_root = "./execution/"
docker_image_prefix = "ipol-demo-"
docker_exec_prefix = "ipol-exec-"
exec_workdir_in_docker = "/workdir"
user_uid_gid = "1000:1000"
gpus = []

[ipol-ipolcore]
port = 3000
user_uid_gid = "1001:1001"
execution_root = "/home/ipol/ipolDevel/shared_folder/run/"
ssh_key_path = "id_ed25519"

[ipol-integration]
port = 3000
user_uid_gid = "1001:1001"
execution_root = "/home/ipol/ipolDevel/shared_folder/run/"
ssh_key_path = "id_ed25519"

[ipol-abeille]
port = 3000
user_uid_gid = "1003:1003"
execution_root = "/home/ipol/ipolDevel/shared_folder/run/"
ssh_key_path = "id_ed25519"
gpus = ["GPU-43d69276-d085-d30b-2a53-b8d276038d12"]
