[default]
compilation_root = "./compilation/"
docker_image_prefix = "ipol-demo-"
docker_exec_prefix = "ipol-exec-"
exec_workdir_in_docker = "/workdir/exec"
user_uid_gid = "1000:1000"
gpus = []
env_vars = {"IPOL_URL"="https://ipolcore.ipol.im"}
max_timeout = 600
limits = {"file"="500MB", "data-form"="500MB"}
exec_network_mode = "bridge"
build_network_mode = "bridge"

[ipol-ipolcore]
port = 3000
user_uid_gid = "1001:1001"
# for ipolcore and integration, we need to avoid collision so we run in separate subnets
exec_network_mode = "prod"
build_network_mode = "prod"

[ipol-integration]
port = 10010
user_uid_gid = "1005:1005"
env_vars = {"IPOL_URL"="https://integration.ipol.im"}
# for ipolcore and integration, we need to avoid collision so we run in separate subnets
exec_network_mode = "integration"
build_network_mode = "integration"

[ipol-limule]
port = 3000
user_uid_gid = "1005:1005"

[ipol-limule-gpu]
port = 3001
user_uid_gid = "1005:1005"
gpus = ["GPU-43d69276-d085-d30b-2a53-b8d276038d12"]
