[default]
compilation_root = "./compilation/"
docker_image_prefix = "ipol-demo-"
docker_exec_prefix = "ipol-exec-"
exec_workdir_in_docker = "/workdir/exec"
user_uid_gid = "1000:1000"
gpus = []
env_vars = {"IPOL_URL"="https://ipolcore.ipol.im"}
ssh_key_path = "id_ed25519"
max_timeout = 600
limits = {"file"="500MB", "data-form"="500MB"}

[ipol-ipolcore]
port = 3000
user_uid_gid = "1001:1001"

[ipol-integration]
port = 3000
user_uid_gid = "1001:1001"
env_vars = {"IPOL_URL"="https://integration.ipol.im"}

[ipol-limule]
port = 3000
user_uid_gid = "1005:1005"

[ipol-limule-gpu]
port = 3001
user_uid_gid = "1005:1005"
gpus = ["GPU-43d69276-d085-d30b-2a53-b8d276038d12"]
