[pytest]
minversion = 8.0
DJANGO_SETTINGS_MODULE = ControlPanel.test_settings
pythonpath = .
testpaths = tests
addopts = -v --tb=short
env =
    D:DJANGO_SETTINGS_MODULE = ControlPanel.test_settings
    D:IPOL_HOST = localhost
    D:IPOL_URL = http://localhost:8000
