#!/usr/bin/env bash

# usage:
# dockerize <your command> [and] [its] [arguments]
#   no need to escape the command

set -u
set -e

volumes="--volume $(realpath .):/workdir/exec"

if [ -z ${bin+x} ]; then
    # we are at build time
    image=$(cat ../bin/dockerizer-image)
    args="$@"
else
    # we are at run time
    image=$(cat $bin/dockerizer-image)
    args=""
    for s in "$@"; do
        # /!\ here we rely on the fact that IPOL's venv are located at $bin/venv
        s="$(echo "$s" | sed "s|$bin/venv|/workdir/venv/|g")"
        s="$(echo "$s" | sed "s|${bin}venv|/workdir/venv/|g")"

        # then, replace the path to $bin and $demoextras to the volumes mount points
        s="$(echo "$s" | sed "s|$bin|/workdir/bin/|g")"
        s="$(echo "$s" | sed "s|$demoextras|/workdir/demoextras|g")"
        args="$args \"$s\""
    done

    if [ -d $bin ]; then
        volumes="$volumes --volume $(realpath $bin):/workdir/bin:ro"
    fi
    if [ -d $demoextras ]; then
        volumes="$volumes --volume $(realpath $demoextras):/workdir/demoextras:ro"
    fi
fi

docker run --rm --user $(id -u):$(id -g) $volumes $image bash -c "$args"

