name: Python

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          # required to test the conversion module
          sudo apt-get install -y ffmpeg

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r ipol_demo/modules/core/requirements.txt

      - name: Test core
        run: |
          cd ipol_demo/modules/core
          python -m pytest tests

  style-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff~=0.0.0 isort~=5.0 black~=23.0

      - name: ruff
        if: success() || failure()
        run: |
          ruff . --show-source

      - name: isort
        if: success() || failure()
        run: |
          isort --check cp2 ipol_demo

      - name: black
        if: success() || failure()
        run: |
          black --check cp2 ipol_demo
